EburyTest/force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EburyTest/force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/BypassFlow__c.field-meta.xml
<CustomField>
    <fullName>BypassFlow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassFlow</label>
    <type>Checkbox</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

EburyTest/force-app/main/default/globalValueSets/Currency_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <description>All currency code from fixer.io</description>
    <masterLabel>Currency Code</masterLabel>
</GlobalValueSet>

EburyTest/force-app/main/default/classes/MainTradeHelper_Test.cls
@isTest
public class MainTradeHelper_Test {
    
    @TestSetup
    static void makeData(){        
        List<Trade__c> trades= new List<Trade__c>();
        Trade__c trade1 = new Trade__c();
        trade1.Buy_Currency__c = 'USD';
        trade1.Date_Booked__c = Datetime.now();
        trade1.Rate__c = 1.1;
        trade1.Sell_Amount__c = 100;
        trade1.Sell_Currency__c = 'EUR';
        trade1.BypassFlow__c = true;
        trades.add(trade1);

        Trade__c trade2 = new Trade__c();
        trade2.Buy_Currency__c = 'EUR';
        trade2.Date_Booked__c = Datetime.now();
        trade2.Rate__c = 0.98;
        trade2.Sell_Amount__c = 100;
        trade2.BypassFlow__c = true;
        trade2.Sell_Currency__c = 'USD';
        trades.add(trade2);
        
        insert trades;
    }

    @isTest
    public static void test_getTrades() {
        Test.startTest();
        List<Trade__c> trades = MainTradeHelper.getTrades();
        Test.stopTest();
        System.assertEquals(2, trades.size());
    }

    @isTest
    public static void test_getGlobalPicklist(){
        Test.startTest();
        List<String> picklist = MainTradeHelper.getGlobalPicklist();
        Test.stopTest();
        System.assert(picklist.size()>0);
        System.assert(picklist.contains('USD'));
    }

    @isTest
    public static void test_createTrade(){
        Test.startTest();
        String response = MainTradeHelper.createTrade('USD', 'EUR', '100', '1.1');
        String response2 = MainTradeHelper.createTrade('EUR', 'USD', '-1', '0.98');
        String response3 = MainTradeHelper.createTrade('EUR', 'USD', '1', '-0.98');
        Test.stopTest();
        System.assertEquals('Success', response);
        System.assert(response2.contains('Error'));
        System.assert(response3.contains('Error'));
    }


    @IsTest 
    private static void testApexSimpleContinuationPassingDataForLWC() {
        String mockResponseBody = '{"rates": {"USD": 1.1, "EUR": 0.98}}';

        Test.startTest();
        Continuation con = (Continuation) MainTradeHelper.rateRequest('EUR','USD');
        Test.stopTest();
        
        // Verify that the continuation has the correct number of requests
        Map<String, HttpRequest> requests = con.getRequests();
        System.assertEquals(1, requests.size(), 'The number of requests associated to the Continuation is not correct');

        // Create a mock response
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        response.setBody(mockResponseBody);

        Test.setContinuationResponse(MainTradeHelper.contState, response);

        List<String> labels = new List<String>{MainTradeHelper.contState};

        String result = JSON.serialize(MainTradeHelper.rateResponse(labels,MainTradeHelper.contlabel));

        system.debug(result);
        
        System.assert(result.contains('"EUR":0.98'), 'Continuation failed: response body not valid');
        System.assert(result.contains('"USD":1.1'), 'Continuation failed: response body not valid');
    }
}