EburyTest/force-app/main/default/objects/PicklistSource__mdt/PicklistSource__mdt.object-meta.xml
<CustomObject>
    <label>PicklistSource</label>
    <pluralLabel>PicklistSources</pluralLabel>
</CustomObject>

EburyTest/force-app/main/default/objects/PicklistSource__mdt/fields/SObject_Field__c.field-meta.xml
<CustomField>
    <fullName>SObject_Field__c</fullName>
    <label>SObject Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

EburyTest/force-app/main/default/objects/PicklistSource__mdt/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <label>SObject Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EburyTest/force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <formula>Sell_Amount__c  *  Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/BypassFlow__c.field-meta.xml
<CustomField>
    <fullName>BypassFlow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassFlow</label>
    <type>Checkbox</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

EburyTest/force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

EburyTest/force-app/main/default/globalValueSets/Currency_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
        <default>true</default>
        <label>USD</label>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <description>All currency code from fixer.io</description>
    <masterLabel>Currency Code</masterLabel>
</GlobalValueSet>

EburyTest/force-app/main/default/classes/MainTradeHelper.cls
public with sharing class MainTradeHelper {

   final static String URL_FIXER_IO = 'https://api.apilayer.com/fixer/latest';
   @TestVisible
   private static String contState;
   @TestVisible
   private static String contlabel;
 
   @AuraEnabled(cacheable = true)
   public static List<Trade__c> getTrades(){
    return [SELECT Id,Sell_Currency__c,Sell_Amount__c,Rate__c,Buy_Currency__c,Buy_Amount__c,Date_Booked__c  FROM Trade__c ORDER BY Date_Booked__c DESC];
   }

   @AuraEnabled(cacheable = true continuation=true)
   public static Object rateRequest(String base, String exchange){
      Continuation con = new Continuation(20);
      con.continuationMethod='rateResponse';

      String fixerEndpoint = URL_FIXER_IO;
      fixerEndpoint += '?base=' + base;
      fixerEndpoint += '&symbols=' + exchange;

      // Create callout request
      HttpRequest req = new HttpRequest();
      req.setMethod('GET');
      req.setEndpoint(fixerEndpoint);
      req.setHeader('apikey', 'bbK6hlWdYVsU4rFikPiDVysRy6XJjYYB');

      contState = con.addHttpRequest(req);
      contlabel ='this is for test';
      con.state = contState;
      return con;
   }

   @AuraEnabled(cacheable = true)
   public static Object rateResponse(List<String> labels, Object state) {
      HttpResponse response = Continuation.getResponse(labels[0]);
      System.debug('Response: ' + response.getBody());
      if(response.getStatusCode() == 200) {
         Map<String,Object> result = ( Map<String,Object>)JSON.deserializeUntyped(response.getBody());         

         return result.get('rates');
      } else {
         return null;
      }     
   }

   @AuraEnabled
   public static List<String> getGlobalPicklist(){
      List<String>  values = new List<String>();
      List<PicklistSource__mdt> picklistNames = [SELECT SObject_Field__c,SObject_Name__c FROM PicklistSource__mdt];
      if(picklistNames.size() > 0){
         List<Schema.PicklistEntry> ple = Schema.getGlobalDescribe().get(picklistNames[0].SObject_Name__c).getDescribe().fields.getMap().get(picklistNames[0].SObject_Field__c).getDescribe().getPicklistValues();
         for(Schema.PicklistEntry p : ple){
            if(p.isActive()){
               values.add(p.getLabel());
            }
         }
         return values;
      }
      return new List<String>();
   }

    @AuraEnabled
    public static String createTrade(String sellCurrency, String buyCurrency, String sellAmount, String rate){
      Trade__c trade = new Trade__c();
      trade.Sell_Currency__c = sellCurrency;
      trade.Buy_Currency__c = buyCurrency;
      trade.Sell_Amount__c = Decimal.valueOf(sellAmount);
      trade.Date_Booked__c = Datetime.now();
      trade.Rate__c = Decimal.valueOf(rate);
      if(Test.isRunningTest()){
         trade.BypassFlow__c = true;
      }   

      Database.SaveResult result = Database.insert(trade, false);
      if(result.isSuccess()){
            return 'Success';
      }else{
         String errorMessage = 'Error ';
         for(Database.Error error : result.getErrors()){
            errorMessage += error.getMessage() + ' ';
         }
            return errorMessage;
      }
    }
}